# -*- coding: utf-8 -*-
"""RL_lab_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15uVTuQIj70z_4ldfsaFlNncXAbjxVKOY
"""

import numpy as np

"""Zadanie 1"""

a = np.array([1,3,5,2,7])
a

b = np.array([1,3,5.0,2,7])
b

b = np.array([3.14, 4, 2, 3],dtype=int)
b

c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c

d=np.array([[-3.0,2.3],[0.1,5.0],[8.0,11.0]])
d

e=np.array([[[2,4],[1,2],[8,9]],[[7,6],[-3,4],[0,8]]])
e

"""Zadanie 2"""

a.ndim,b.ndim,c.ndim,d.ndim,e.ndim

a.shape,b.shape,c.shape,d.shape,e.shape

a.size, b.size,c.size,d.size,e.size

a.dtype,b.dtype,c.dtype,d.dtype,e.dtype

a.itemsize,b.itemsize,c.itemsize,d.itemsize,e.itemsize

a.nbytes,b.nbytes,c.nbytes,d.nbytes,e.nbytes