# -*- coding: utf-8 -*-
"""RL_lab_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15uVTuQIj70z_4ldfsaFlNncXAbjxVKOY
"""

import numpy as np

"""Zadanie 1"""

a = np.array([1,3,5,2,7])
a

b = np.array([1,3,5.0,2,7])
b

b = np.array([3.14, 4, 2, 3],dtype=int)
b

c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c

d=np.array([[-3.0,2.3],[0.1,5.0],[8.0,11.0]])
d

e=np.array([[[2,4],[1,2],[8,9]],[[7,6],[-3,4],[0,8]]])
e

"""Zadanie 2"""

a.ndim,b.ndim,c.ndim,d.ndim,e.ndim

a.shape,b.shape,c.shape,d.shape,e.shape

a.size, b.size,c.size,d.size,e.size

a.dtype,b.dtype,c.dtype,d.dtype,e.dtype

a.itemsize,b.itemsize,c.itemsize,d.itemsize,e.itemsize

a.nbytes,b.nbytes,c.nbytes,d.nbytes,e.nbytes

"""Zadanie 3

"""

X1 = np.random.random((4,3))

X2 = np.zeros((2,1))

X3 = np.full((6,2,1),2)

X4 = np.random.randint(0,7,(5,8))

X5 = np.eye(5)

X1

X2

X3

X4

X5

"""ZADANIE TENSORY"""

A = np.array([[[1],[2]],[[1],[2]],[[1],[2]]])
A.shape

A = np.array([[[1,2]],[[1,2]],[[1,2]]])
A.shape

A = np.array([[[1,2,3],[1,2,3]]])
A.shape

A = np.array([[[1,2,3]],[[1,2,3]]])
A.shape

A = np.array([[[[[1],[2],[3]]],[[[1],[2],[3]]]]])
A.shape

"""Zadanie 4"""

A = np.random.randint(0,6,(4,5))
A

A[1,4]

A[1:3,4]

B = A[1:3,3:5]
B



B = A[1:3,3:5].copy()
B

B[0,0]=100

B

A

B = A[:,1:3]
B

A[1:3,3:5]

A[1:,3:]



"""Zadanie 4"""

A = np.random.randint(0,6,(4,5))
A

B = A[:,1:3]
B

B1 = A[:,1:3].copy()
B1

C = A[1:3,1:5]
C

C1 = A[1:3,1:5].copy()
C1

"""Zadanie 5"""

D = np.array(np.arange(0,12))
D

D.shape

print(D.reshape(2,6))

print(D.reshape(3,4))

print(D.reshape(3,4,1))

print(D.reshape(3,1,2,1,2))

"""Zadanie 5 (przy 24)"""



D = np.array(np.arange(0,24))
D

print(D.reshape(4,6))

print(D.reshape(6,4))

print(D.reshape(8,3))

print(D.reshape(3,8))

print(D.reshape(2,12))

print(D.reshape(12,2))

print(D.reshape(3,8))

print(D.reshape(8,3))

print(D.reshape(2,2,2,3))

print(D.reshape(2,2,3,2))

print(D.reshape(2,3,2,2))

print(D.reshape(3,2,2,2))

print(D.reshape(2,4,3))

print(D.reshape(2,3,4))

print(D.reshape(3,4,2))

print(D.reshape(3,2,4))

print(D.reshape(4,2,3))

print(D.reshape(4,3,2))

print(D.reshape(2,6,2))

print(D.reshape(2,2,6))

print(D.reshape(6,2,2))

"""Zadanie 6"""

c = np.array([[2,4],[1,2]])
d = np.array([[-3,5],[-7,8]])


print("c=\n",c)
print("d=\n",d)
print("c.shape=",c.shape)
print("d.shape=",d.shape)
print(np.concatenate([c,d],axis=0))
print(np.concatenate([c,d],axis=1))
print(np.concatenate([d,c],axis=0))
print(np.concatenate([d,c],axis=1))

"""zadanie 7

"""

c*d

d+6
d

d*8
d

d-8
d

d/8
d

abs(8)
d

np.exp(d)
d

np.power(d,4)
d

A = np.array([[1],[1]])
A

A = A+X2
A

A = A-X2
A

A = A*X2
A

"""Zadadnie 8"""

c = np.array([[1,1,1],[1,1,1]])
d = np.array([[0,1,2]])

c+d

c= np.array([[0],[1],[2]])
d = np.array([[0,1,2]])
c+d