# -*- coding: utf-8 -*-
"""RegresjaLiniowa_BostonDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGwgc130ezQjjywT5ZckOl0A6t7m7RIU

**Zadanie 1**
"""

import pandas as pd
import numpy as np
data = pd.read_csv('Boston.csv')

print("Data:",data,end="\n")

data.info()

data.loc[:,'rm'],data.loc[:,'medv']

rm = np.array(data.loc[:,'rm'])
medv = np.array(data.loc[:,'medv'])

rm

medv

import matplotlib.pyplot as plt

x_value = np.array(data['rm'])
y_value = np.array(data['medv'])

plt.scatter(rm,medv,marker="+",color='red')
plt.xlabel('rm')
plt.ylabel('medv')
plt.show()